/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.elcalamot.kalamus.vistas;

import com.elcalamot.kalamus.model_planetas.FuncionesModelo_Planetas;
import com.elcalamot.kalamus.model_planetas.Sistemas;
import static java.awt.event.MouseEvent.BUTTON1;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author A200238614
 */
public class AddBeing extends javax.swing.JFrame {

    /**
     * Creates new form AddPlanet
     */
    public AddBeing() {
        initComponents();
        Sistemas sis = Sistemas.getInstance();
        this.setLocationRelativeTo(null);



        ArrayList<String> listb = sis.nombresEssers();
        planetexist.append("No disponibles: \n");
        for (String linea : listb) {
            planetexist.append(linea + "\n");

        }

    }

    public void habilitarBoton() {
        if (!this.nombre1.getText().isEmpty() && !this.galaxia1.getText().isEmpty()) {

            this.añadirbeing.setEnabled(true);

        } else {
            this.añadirbeing.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mensaje = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        mensajepanel = new javax.swing.JTextArea();
        base = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        planetexist = new javax.swing.JTextArea();
        nombre = new javax.swing.JLabel();
        nombre1 = new javax.swing.JTextField();
        galaxia1 = new javax.swing.JTextField();
        nombre2 = new javax.swing.JLabel();
        planeta2 = new javax.swing.JLabel();
        esser1 = new javax.swing.JComboBox<>();
        esser = new javax.swing.JLabel();
        humans = new javax.swing.JPanel();
        nombre3 = new javax.swing.JLabel();
        nombre4 = new javax.swing.JLabel();
        galaxia2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        linea = new javax.swing.JLabel();
        andorianos = new javax.swing.JPanel();
        rango = new javax.swing.JLabel();
        rango1 = new javax.swing.JComboBox<>();
        ferengi = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        añadirbeing = new javax.swing.JButton();

        this.setLocationRelativeTo(null);
        mensaje.setMinimumSize(new java.awt.Dimension(400, 300));
        mensaje.getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        mensajepanel.setEditable(false);
        mensajepanel.setBackground(new java.awt.Color(102, 102, 102));
        mensajepanel.setColumns(20);
        mensajepanel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        mensajepanel.setLineWrap(true);
        mensajepanel.setRows(5);
        jScrollPane2.setViewportView(mensajepanel);

        mensaje.getContentPane().add(jScrollPane2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir Planetas");
        setMinimumSize(new java.awt.Dimension(820, 500));
        setSize(new java.awt.Dimension(820, 500));

        base.setBackground(new java.awt.Color(51, 51, 51));
        base.setMinimumSize(new java.awt.Dimension(820, 500));
        base.setPreferredSize(new java.awt.Dimension(820, 500));

        planetexist.setEditable(false);
        planetexist.setBackground(new java.awt.Color(204, 204, 204));
        planetexist.setColumns(20);
        planetexist.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        planetexist.setForeground(new java.awt.Color(51, 51, 51));
        planetexist.setRows(5);
        planetexist.setAutoscrolls(false);
        planetexist.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        planetexist.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(planetexist);

        nombre.setBackground(new java.awt.Color(204, 204, 204));
        nombre.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        nombre.setForeground(new java.awt.Color(204, 204, 204));
        nombre.setText("DATOS");

        nombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombre1KeyReleased(evt);
            }
        });

        galaxia1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                galaxia1KeyReleased(evt);
            }
        });

        nombre2.setBackground(new java.awt.Color(204, 204, 204));
        nombre2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nombre2.setForeground(new java.awt.Color(204, 204, 204));
        nombre2.setText("Nombre:");

        planeta2.setBackground(new java.awt.Color(204, 204, 204));
        planeta2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        planeta2.setForeground(new java.awt.Color(204, 204, 204));
        planeta2.setText("Planeta:");

        esser1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HUMA", "ANDORIA", "FERENGI", "VULCANIA", "KLINGON", "NIBIRIA" }));
        esser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esser1ActionPerformed(evt);
            }
        });

        esser.setBackground(new java.awt.Color(204, 204, 204));
        esser.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        esser.setForeground(new java.awt.Color(204, 204, 204));
        esser.setText("Esser:");

        humans.setBackground(new java.awt.Color(51, 51, 51));

        nombre3.setBackground(new java.awt.Color(204, 204, 204));
        nombre3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nombre3.setForeground(new java.awt.Color(204, 204, 204));
        nombre3.setText("Edad:");

        nombre4.setBackground(new java.awt.Color(204, 204, 204));
        nombre4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nombre4.setForeground(new java.awt.Color(204, 204, 204));
        nombre4.setText("Sexo:");

        galaxia2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                galaxia2KeyReleased(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MACULI", "FEMENI", " " }));

        javax.swing.GroupLayout humansLayout = new javax.swing.GroupLayout(humans);
        humans.setLayout(humansLayout);
        humansLayout.setHorizontalGroup(
            humansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(humansLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(humansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(humansLayout.createSequentialGroup()
                        .addComponent(nombre3)
                        .addGap(18, 18, 18)
                        .addComponent(galaxia2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(humansLayout.createSequentialGroup()
                        .addComponent(nombre4)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        humansLayout.setVerticalGroup(
            humansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(humansLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(humansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre3)
                    .addComponent(galaxia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(humansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(196, Short.MAX_VALUE))
        );

        linea.setBackground(new java.awt.Color(204, 204, 204));
        linea.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        linea.setForeground(new java.awt.Color(204, 204, 204));
        linea.setText("---------------------------------------------------------------------------------------------------------");

        andorianos.setBackground(new java.awt.Color(51, 51, 51));

        rango.setBackground(new java.awt.Color(204, 204, 204));
        rango.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rango.setForeground(new java.awt.Color(204, 204, 204));
        rango.setText("Rango:");

        rango1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DEFENSOR", "LLUITADOR", "CAVALLER", "ENTRENADOR" }));

        javax.swing.GroupLayout andorianosLayout = new javax.swing.GroupLayout(andorianos);
        andorianos.setLayout(andorianosLayout);
        andorianosLayout.setHorizontalGroup(
            andorianosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(andorianosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rango)
                .addGap(18, 18, 18)
                .addComponent(rango1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        andorianosLayout.setVerticalGroup(
            andorianosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(andorianosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(andorianosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rango)
                    .addComponent(rango1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ferengiLayout = new javax.swing.GroupLayout(ferengi);
        ferengi.setLayout(ferengiLayout);
        ferengiLayout.setHorizontalGroup(
            ferengiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ferengiLayout.setVerticalGroup(
            ferengiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout baseLayout = new javax.swing.GroupLayout(base);
        base.setLayout(baseLayout);
        baseLayout.setHorizontalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(baseLayout.createSequentialGroup()
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(planeta2)
                            .addComponent(esser))
                        .addGap(18, 18, 18)
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(esser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(galaxia1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(627, 627, 627))
                    .addGroup(baseLayout.createSequentialGroup()
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, baseLayout.createSequentialGroup()
                                .addComponent(nombre2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(baseLayout.createSequentialGroup()
                                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ferengi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(linea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(andorianos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(humans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        baseLayout.setVerticalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLayout.createSequentialGroup()
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(baseLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(baseLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(nombre)
                        .addGap(18, 18, 18)
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre2)
                            .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(galaxia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(planeta2))
                        .addGap(18, 18, 18)
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(esser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(esser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(linea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(humans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(andorianos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ferengi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );

        getContentPane().add(base, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(820, 35));
        jPanel1.setPreferredSize(new java.awt.Dimension(820, 35));

        añadirbeing.setText("Añadir");
        añadirbeing.setEnabled(false);
        añadirbeing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                añadirbeingMouseClicked(evt);
            }
        });
        jPanel1.add(añadirbeing);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void añadirbeingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_añadirbeingMouseClicked
        if (evt.getButton() == BUTTON1) {

            String nombre = this.nombre1.getText();
            String planeta = this.planeta2.getText();

        }


    }//GEN-LAST:event_añadirbeingMouseClicked

    private void nombre1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre1KeyReleased
        // TODO add your handling code here:
        habilitarBoton();

    }//GEN-LAST:event_nombre1KeyReleased

    private void galaxia1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_galaxia1KeyReleased
        habilitarBoton();
    }//GEN-LAST:event_galaxia1KeyReleased

    private void esser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esser1ActionPerformed
        if (this.esser1.getSelectedItem().toString().equalsIgnoreCase("huma")) {
            this.humans.setVisible(true);
            this.andorianos.setVisible(false);
            this.ferengi.setVisible(false);
            base.repaint();
            base.revalidate();
            System.out.println("-");
        } else if (this.esser1.getSelectedItem().toString().equalsIgnoreCase("andoria")) {
            this.humans.setVisible(false);
            this.andorianos.setVisible(true);
            this.ferengi.setVisible(false);
            base.repaint();
            base.revalidate();
            System.out.println("--");
        } else if (this.esser1.getSelectedItem().toString().equalsIgnoreCase("klingon")) {

        } else if (this.esser1.getSelectedItem().toString().equalsIgnoreCase("ferengi")) {
            this.humans.setVisible(false);
            this.andorianos.setVisible(false);
            this.ferengi.setVisible(true);
            base.repaint();
            base.revalidate();
            System.out.println("---");

        } else if (this.esser1.getSelectedItem().toString().equalsIgnoreCase("nibiria")) {

        } else if (this.esser1.getSelectedItem().toString().equalsIgnoreCase("vulcania")) {

        }
    }//GEN-LAST:event_esser1ActionPerformed

    private void galaxia2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_galaxia2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_galaxia2KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBeing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBeing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBeing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBeing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBeing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel andorianos;
    private javax.swing.JButton añadirbeing;
    private javax.swing.JPanel base;
    private javax.swing.JLabel esser;
    private javax.swing.JComboBox<String> esser1;
    private javax.swing.JPanel ferengi;
    private javax.swing.JTextField galaxia1;
    private javax.swing.JTextField galaxia2;
    private javax.swing.JPanel humans;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel linea;
    private javax.swing.JDialog mensaje;
    private javax.swing.JTextArea mensajepanel;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField nombre1;
    private javax.swing.JLabel nombre2;
    private javax.swing.JLabel nombre3;
    private javax.swing.JLabel nombre4;
    private javax.swing.JLabel planeta2;
    private javax.swing.JTextArea planetexist;
    private javax.swing.JLabel rango;
    private javax.swing.JComboBox<String> rango1;
    // End of variables declaration//GEN-END:variables
}
