/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.elcalamot.kalamus.vistas;

import com.elcalamot.kalamus.model_planetas.FuncionesModelo_Planetas;
import com.elcalamot.kalamus.model_planetas.Sistemas;
import static java.awt.event.MouseEvent.BUTTON1;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author A200238614
 */
public class AddPlanet extends javax.swing.JFrame {

    /**
     * Creates new form AddPlanet
     */
    public AddPlanet() {
        initComponents();
        Sistemas sis = Sistemas.getInstance();
        this.setLocationRelativeTo(null);

        ArrayList<String> listp = sis.nombresPlanetas();
        planetexist.append("No disponibles: \n");
        for (String linea : listp) {
            planetexist.append(linea + "\n");

        }

    }

    public void habilitarBoton() {
        if (!this.nombre1.getText().isEmpty() && !this.galaxia1.getText().isEmpty()) {

            this.añadirplaneta.setEnabled(true);

        } else {
            this.añadirplaneta.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mensaje = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        mensajepanel = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        planetexist = new javax.swing.JTextArea();
        nombre = new javax.swing.JLabel();
        nombre1 = new javax.swing.JTextField();
        flora = new javax.swing.JLabel();
        galaxia1 = new javax.swing.JTextField();
        habitantes = new javax.swing.JLabel();
        clima = new javax.swing.JLabel();
        clima1 = new javax.swing.JComboBox<>();
        nombre2 = new javax.swing.JLabel();
        galaxia2 = new javax.swing.JLabel();
        peces = new javax.swing.JLabel();
        flora1 = new javax.swing.JRadioButton();
        pez1 = new javax.swing.JRadioButton();
        habitants1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        añadirplaneta = new javax.swing.JButton();

        this.setLocationRelativeTo(null);
        mensaje.setTitle("Mensaje");
        mensaje.setMinimumSize(new java.awt.Dimension(400, 300));
        mensaje.getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        mensajepanel.setEditable(false);
        mensajepanel.setBackground(new java.awt.Color(102, 102, 102));
        mensajepanel.setColumns(20);
        mensajepanel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        mensajepanel.setLineWrap(true);
        mensajepanel.setRows(5);
        jScrollPane2.setViewportView(mensajepanel);

        mensaje.getContentPane().add(jScrollPane2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir Planetas");
        setMinimumSize(new java.awt.Dimension(820, 500));
        setSize(new java.awt.Dimension(820, 500));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setMinimumSize(new java.awt.Dimension(820, 500));
        jPanel2.setPreferredSize(new java.awt.Dimension(820, 500));

        planetexist.setEditable(false);
        planetexist.setBackground(new java.awt.Color(204, 204, 204));
        planetexist.setColumns(20);
        planetexist.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        planetexist.setForeground(new java.awt.Color(51, 51, 51));
        planetexist.setRows(5);
        planetexist.setAutoscrolls(false);
        planetexist.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        planetexist.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(planetexist);

        nombre.setBackground(new java.awt.Color(204, 204, 204));
        nombre.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        nombre.setForeground(new java.awt.Color(204, 204, 204));
        nombre.setText("DATOS");

        nombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombre1KeyReleased(evt);
            }
        });

        flora.setBackground(new java.awt.Color(204, 204, 204));
        flora.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        flora.setForeground(new java.awt.Color(204, 204, 204));
        flora.setText("Flora roja:");

        galaxia1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                galaxia1KeyReleased(evt);
            }
        });

        habitantes.setBackground(new java.awt.Color(204, 204, 204));
        habitantes.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        habitantes.setForeground(new java.awt.Color(204, 204, 204));
        habitantes.setText("Habitantes(Maximos):");

        clima.setBackground(new java.awt.Color(204, 204, 204));
        clima.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        clima.setForeground(new java.awt.Color(204, 204, 204));
        clima.setText("Clima:");

        clima1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TEMPERAT", "CALID", "FRED" }));

        nombre2.setBackground(new java.awt.Color(204, 204, 204));
        nombre2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nombre2.setForeground(new java.awt.Color(204, 204, 204));
        nombre2.setText("Nombre:");

        galaxia2.setBackground(new java.awt.Color(204, 204, 204));
        galaxia2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        galaxia2.setForeground(new java.awt.Color(204, 204, 204));
        galaxia2.setText("Galaxia:");

        peces.setBackground(new java.awt.Color(204, 204, 204));
        peces.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        peces.setForeground(new java.awt.Color(204, 204, 204));
        peces.setText("Fauna aquatica:");

        habitants1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nombre2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(galaxia2)
                        .addGap(18, 18, 18)
                        .addComponent(galaxia1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(habitantes)
                        .addGap(18, 18, 18)
                        .addComponent(habitants1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(clima)
                        .addGap(18, 18, 18)
                        .addComponent(clima1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nombre)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(peces)
                        .addGap(18, 18, 18)
                        .addComponent(pez1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(flora)
                        .addGap(18, 18, 18)
                        .addComponent(flora1)))
                .addContainerGap(337, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pez1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(nombre)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(nombre2)
                                            .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(galaxia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(galaxia2))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(habitantes)
                                            .addComponent(habitants1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(clima)
                                            .addComponent(clima1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(flora))
                                    .addComponent(flora1))
                                .addGap(18, 18, 18)
                                .addComponent(peces)))
                        .addGap(0, 175, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(820, 35));
        jPanel1.setPreferredSize(new java.awt.Dimension(820, 35));

        añadirplaneta.setText("Añadir");
        añadirplaneta.setEnabled(false);
        añadirplaneta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                añadirplanetaMouseClicked(evt);
            }
        });
        jPanel1.add(añadirplaneta);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void añadirplanetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_añadirplanetaMouseClicked
        if (evt.getButton() == BUTTON1) {

            String nombre = this.nombre1.getText();
            String galaxia = this.galaxia1.getText();
            String habitantes = this.habitants1.getValue().toString();
            String clima = this.clima1.getSelectedItem().toString();
            boolean flora = this.flora1.isSelected();
            boolean pez = this.pez1.isSelected();
            String dato1 = "no";
            String dato2 = "no";
            if (flora == true) {
                dato1 = "yes";
            } else if (flora == false) {
                dato1 = "no";
            }
            if (pez == true) {
                dato2 = "yes";
            } else if (pez == false) {
                dato2 = "no";
            }
            try {
                String[] datos = {"", "", nombre, galaxia, habitantes, clima, dato1, dato2};
                String out = "ERROR: Campo vacio o sin el valor esperado.";
                if (!nombre.isBlank() && !galaxia.isBlank() && !habitantes.isBlank()) {
                    out = FuncionesModelo_Planetas.crearPlaneta(datos, "jframe");
                }

                this.mensajepanel.append(out);
                this.mensaje.setVisible(true);
                
            } catch (IOException | ClassNotFoundException | SQLException e) {
                System.out.println(e.getMessage());
            }

            this.nombre1.setText(null);
            this.galaxia1.setText(null);
            this.flora1.setSelected(false);
            this.pez1.setSelected(false);

        }


    }//GEN-LAST:event_añadirplanetaMouseClicked

    private void nombre1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre1KeyReleased
        // TODO add your handling code here:
        habilitarBoton();

    }//GEN-LAST:event_nombre1KeyReleased

    private void galaxia1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_galaxia1KeyReleased
        habilitarBoton();
    }//GEN-LAST:event_galaxia1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPlanet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPlanet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPlanet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPlanet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPlanet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadirplaneta;
    private javax.swing.JLabel clima;
    private javax.swing.JComboBox<String> clima1;
    private javax.swing.JLabel flora;
    private javax.swing.JRadioButton flora1;
    private javax.swing.JTextField galaxia1;
    private javax.swing.JLabel galaxia2;
    private javax.swing.JLabel habitantes;
    private javax.swing.JSpinner habitants1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JDialog mensaje;
    private javax.swing.JTextArea mensajepanel;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField nombre1;
    private javax.swing.JLabel nombre2;
    private javax.swing.JLabel peces;
    private javax.swing.JRadioButton pez1;
    private javax.swing.JTextArea planetexist;
    // End of variables declaration//GEN-END:variables
}
